Using PKG_CHECK_MODULES and PKG_CHECK_EXISTS instead of hand crafted shell code to detect libgsoap++ thru pkg-config.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -618,10 +618,15 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+gSOAP_LIBS
+gSOAP_CFLAGS
 BUILD_EXAMPLES_FALSE
 BUILD_EXAMPLES_TRUE
 STATIC_CLIENTS_FALSE
 STATIC_CLIENTS_TRUE
+PKG_CONFIG_LIBDIR
+PKG_CONFIG_PATH
+PKG_CONFIG
 CXXCPP
 OTOOL64
 OTOOL
@@ -747,7 +752,6 @@ enable_fast_install
 with_gnu_ld
 with_sysroot
 enable_libtool_lock
-with_gnu_ld
 enable_static_clients
 enable_examples
 '
@@ -762,13 +766,13 @@ CPPFLAGS
 CCC
 CC
 CFLAGS
-LDFLAGS
-LIBS
-CPPFLAGS
 CPP
-CPPFLAGS
 CXXCPP
-CPPFLAGS'
+PKG_CONFIG
+PKG_CONFIG_PATH
+PKG_CONFIG_LIBDIR
+gSOAP_CFLAGS
+gSOAP_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1420,6 +1424,14 @@ Some influential environment variables:
   CFLAGS      C compiler flags
   CPP         C preprocessor
   CXXCPP      C++ preprocessor
+  PKG_CONFIG  path to pkg-config utility
+  PKG_CONFIG_PATH
+              directories to add to pkg-config's search path
+  PKG_CONFIG_LIBDIR
+              path overriding pkg-config's built-in search path
+  gSOAP_CFLAGS
+              C compiler flags for gSOAP, overriding pkg-config
+  gSOAP_LIBS  linker flags for gSOAP, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -15375,6 +15387,126 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 
+
+
+
+
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_ac_pt_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_pt_PKG_CONFIG" >&5
+$as_echo "$ac_pt_PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.9.0
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking pkg-config is at least version $_pkg_min_version" >&5
+$as_echo_n "checking pkg-config is at least version $_pkg_min_version... " >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+		PKG_CONFIG=""
+	fi
+fi
+
 # Test whether to build static linked client programs:
 # Check whether --enable-static-clients was given.
 if test "${enable_static_clients+set}" = set; then :
@@ -15430,19 +15562,110 @@ fi
 # gsoapck++  - SOAP C++ Web Services with Cookies Enabled
 # gsoap      - SOAP C Web Services
 
-pkg-config --exists gsoap++ > /dev/null
-if test "$?" == "0" ; then
-  whoson_have_gsoap_cxx="yes"
+if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gsoap++\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gsoap++") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for gSOAP" >&5
+$as_echo_n "checking for gSOAP... " >&6; }
+
+if test -n "$gSOAP_CFLAGS"; then
+    pkg_cv_gSOAP_CFLAGS="$gSOAP_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gsoap++\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gsoap++") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_gSOAP_CFLAGS=`$PKG_CONFIG --cflags "gsoap++" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
 else
-  whoson_have_gsoap_cxx="no"
+  pkg_failed=yes
 fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for library gsoap++" >&5
-$as_echo_n "checking for library gsoap++... " >&6; }
+ else
+    pkg_failed=untried
+fi
+if test -n "$gSOAP_LIBS"; then
+    pkg_cv_gSOAP_LIBS="$gSOAP_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gsoap++\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gsoap++") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_gSOAP_LIBS=`$PKG_CONFIG --libs "gsoap++" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        gSOAP_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "gsoap++" 2>&1`
+        else
+	        gSOAP_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "gsoap++" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$gSOAP_PKG_ERRORS" >&5
+
+	 whoson_have_gsoap_cxx="no"
+
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	 whoson_have_gsoap_cxx="no"
+
+else
+	gSOAP_CFLAGS=$pkg_cv_gSOAP_CFLAGS
+	gSOAP_LIBS=$pkg_cv_gSOAP_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+      GSOAP_LIBS="${pkg_cv_gSOAP_LIBS}"
+      GSOAP_CXXFLAGS="${pkg_cv_gSOAP_CFLAGS}"
+      whoson_have_gsoap_cxx="yes"
+
+fi
+
+fi
+
+if test "x{whoson_have_gsoap_cxx}" = "xno" ; then
+  # Using the standard AC_CHECK_LIB() won't work.
+  for d in /usr/local /usr/local/gsoap /opt /opt/gsoap; do
+    if test -e "$d/lib/libgsoap++.a" ; then
+      GSOAP_LIBS="-L$d/lib -lgsoap++"
+      whoson_have_gsoap_cxx="yes"
+    fi
+    if test -e "$d/include/stdsoap2.h" ; then
+      GSOAP_CXXFLAGS="-I$d/include"
+    fi
+  done
+fi
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether gSOAP was found" >&5
+$as_echo_n "checking whether gSOAP was found... " >&6; }
 if test "x${whoson_have_gsoap_cxx}" == "xyes" ; then
-  GSOAP_LIBS=$(pkg-config --libs gsoap++)
-  GSOAP_CXXFLAGS=$(pkg-config --cflags gsoap++)
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes (libs: ${GSOAP_LDD_FLAGS}, cflags: ${GSOAP_CXX_FLAGS})" >&5
-$as_echo "yes (libs: ${GSOAP_LDD_FLAGS}, cflags: ${GSOAP_CXX_FLAGS})" >&6; }
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes, (libs: ${GSOAP_LIBS}, cxxflags: ${GSOAP_CXXFLAGS})" >&5
+$as_echo "yes, (libs: ${GSOAP_LIBS}, cxxflags: ${GSOAP_CXXFLAGS})" >&6; }
 
 $as_echo "#define HAVE_LIBGSOAP_CXX 1" >>confdefs.h
 
