Added configuration files and utility scripts.

diff --git a/admin/whosonrc b/admin/whosonrc
--- a/admin/whosonrc
+++ b/admin/whosonrc
@@ -1,43 +1,38 @@
 #!/bin/bash
 # 
-# Utility script to be sourced by ~/.bashrc or ~/.bash_logout to handle
-# logon and logoff events.
+# Wrapper for the whoson logon/logoff event handler command. Use whosonp to
+# integrate this script with loginwindow.
 #
 # Author: Anders Lövgren
-# Date:   2012-02-22
+# Date:   2012-03-22
 #
 
-WHOSON_SOAP_ENDPOINT="http://bmc-mtws5.bmcmediatek.uu.se/compdept/websvc/whoson/LogonAccountingService.asmx"
-WHOSON_DEBUG=0
-WHOSON_VERBOSE=0
+WHOSON_GLOB_PREF="/etc/whoson.conf"
+WHOSON_USER_PREF="~/.whoson.conf"
 
-WHOSON_PROGRAM=~/Programs/whoson/usr/local/bin/whoson
+# If program is not in PATH:
+# WHOSON_PROGRAM=/opt/whoson/bin/whoson
 
-function register_logon_event()
-{
-  if [ -x ${WHOSON_PROGRAM} ]; then
-    ${WHOSON_PROGRAM} -i
-  fi
-}
+if [ -e ${WHOSON_USER_PREF} ]; then
+  . ${WHOSON_USER_PREF}
+fi
+if [ -e ${WHOSON_GLOB_PREF} ]; then
+  . ${WHOSON_GLOB_PREF}
+fi
+if [ -z "${WHOSON_SOAP_ENDPOINT}" ]; then
+  export WHOSON_SOAP_ENDPOINT="http://server.example.com/whoson/"
+fi
 
-function register_logoff_event()
-{
-  if [ -x ${WHOSON_PROGRAM} ]; then
-    ${WHOSON_PROGRAM} -o
-  fi
-}
+if [ "${WHOSON_DEBUG}" != "0" ]; then
+  set -x
+fi
+if [ -z "${WHOSON_PROGRAM}" ]; then
+  WHOSON_PROGRAM=$(which whoson)
+fi
 
-case "$1" in
-  logon)
-    register_logon_event
-    ;;
-  logon)
-    register_logoff_event
-    ;;
-  *)
-    echo "usage: $0 logon|logoff"
-    exit 1
-    ;;
-esac
+if ! [ -x ${WHOSON_PROGRAM} ]; then
+  echo "$0: can't find whoson"
+  exit 1
+fi
 
-exit 0
+${WHOSON_PROGRAM} $*
